### ISSUE TITLE
Doesn't work on @vue/cli-beta.15 setup

### ISSUE THREAD

**Issue by Elfayer** [pksunkara/vue-cli-plugin-storybook#2]
I used `vue ui` to run the script `npm run storybook`, it returns an error. Note I use vue-cli default setup and just added vue-cli-plugin-storybook.

```
> my-vue@0.1.0 storybook C:\Users\<user>\Documents\Projects\my-vue\my-vue
> start-storybook -p 6006 -c config/storybook


info @storybook/vue v3.4.6

info

exec: fatal: No such remote 'origin'


=> Loading custom addons config.

=> Loading custom webpack config (full-control mode).

C:\Users\<user>\Documents\Projects\my-vue\my-vue\node_modules\@storybook\core\node_modules\webpack\lib\webpack.js:19
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'mode'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           mode: ...
         }
       })
     ]
    at webpack (C:\Users\<user>\Documents\Projects\my-vue\my-vue\node_modules\@storybook\core\node_modules\webpack\lib\webpack.js:19:9)
    at exports.default (C:\Users\<user>\Documents\Projects\my-vue\my-vue\node_modules\@storybook\core\dist\server\middleware.js:29:40)
    at buildDev (C:\Users\<user>\Documents\Projects\my-vue\my-vue\node_modules\@storybook\core\dist\server\build-dev.js:163:36)
    at Object.<anonymous> (C:\Users\<user>\Documents\Projects\my-vue\my-vue\node_modules\@storybook\vue\dist\server\index.js:23:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\<user>\Documents\Projects\my-vue\my-vue\node_modules\@storybook\vue\bin\index.js:3:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! my-vue@0.1.0 storybook: `start-storybook -p 6006 -c config/storybook`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-vue@0.1.0 storybook script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2018-06-04T06_32_05_255Z-debug.log
```

**Comment by pksunkara** [comment]
0.3.0 is released which should be working with the latest cli release candidates.
